# Generated by Django 3.2.9 on 2022-02-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20220202_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(default='Bielefeld', max_length=20, verbose_name='hometown'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='Test@email.de', max_length=20, verbose_name='email'),
        ),
    ]
