# Generated by Django 3.2.9 on 2022-02-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20220203_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/avatar/default.jpg', null=True, upload_to='avatar', verbose_name='Avatar'),
        ),
    ]
